title: Priyanshu
description: Portfolio & Projects
theme: jekyll-theme-minimal
show_downloads: false

# Site settings
author: Priyanshu DevHare
email: priyanshu.arctichare.buisness@gmail.com
baseurl: ""
url: "https://arcticdevloperhare.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
nav_links:
  - name: Home
    url: /
  - name: Projects
    url: /projects
  - name: About
    url: /about

github:
  repository_url: https://github.com/ArcticDevloperHare/ArcticDevloperHare.github.io
  is_user_page: true
